name: Auto Publish to npm

on:
  push:
    branches: [main, master]
    paths:
      - 'package.json'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.version-check.outputs.changed }}
      new-version: ${{ steps.version-check.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check version change
        id: version-check
        run: |
          # 获取当前版本
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          # 检查上一次提交的版本
          git checkout HEAD~1 -- package.json 2>/dev/null || echo "First commit"
          PREV_VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")

          # 恢复当前版本
          git checkout HEAD -- package.json

          echo "Previous version: $PREV_VERSION"
          echo "Current version: $CURRENT_VERSION"

          if [ "$CURRENT_VERSION" != "$PREV_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Version changed from $PREV_VERSION to $CURRENT_VERSION"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Version unchanged"
          fi

  publish:
    needs: check-version
    runs-on: ubuntu-latest
    if: needs.check-version.outputs.version-changed == 'true'
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run quality checks
        run: |
          pnpm run lint
          pnpm run format:check
          pnpm run build

      - name: Create git tag
        run: |
          VERSION=${{ needs.check-version.outputs.new-version }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 检查标签是否已存在
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists, skipping tag creation"
          else
            git tag -a "v$VERSION" -m "Release version $VERSION"
            git push origin "v$VERSION"
          fi

      - name: Publish to npm
        run: |
          # 检查包是否已发布
          if npm view @jackie733/sucker@${{ needs.check-version.outputs.new-version }} version 2>/dev/null; then
            echo "Package version ${{ needs.check-version.outputs.new-version }} already exists on npm"
            exit 1
          fi
          pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SUCKER_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check-version.outputs.new-version }}
          name: Release v${{ needs.check-version.outputs.new-version }}
          body: |
            ## Changes in v${{ needs.check-version.outputs.new-version }}

            Auto-generated release for version ${{ needs.check-version.outputs.new-version }}

            ### Installation
            ```bash
            npm install @jackie733/sucker@${{ needs.check-version.outputs.new-version }}
            # or
            pnpm add @jackie733/sucker@${{ needs.check-version.outputs.new-version }}
            # or
            yarn add @jackie733/sucker@${{ needs.check-version.outputs.new-version }}
            ```

            ### What's Changed
            - Package version updated to ${{ needs.check-version.outputs.new-version }}
            - View full changelog: https://github.com/${{ github.repository }}/compare/v${{ needs.check-version.outputs.new-version }}...HEAD
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
